spring:
  profiles.active: dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always

logging:
  level:
    root: info
    com.dmk.scrimdor: debug
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
